// @vitest-environment node
/**
 * Acceptance checks for the umbrella artifact gate — the executable form of
 * the plan's contract. Every check below was written against the Phase 1
 * stubs and is unskipped one concern at a time in Phase 3.
 *
 * The checks are hermetic by design: the check-mode tests build a fake
 * "committed" root in a temp directory and regenerate from the real skill
 * tree (read-only), so no test ever modifies the committed artifact on disk.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { buildPublication, defaultSkillsRoot } from '../../../scripts/generate-agent-skills.mjs';
import { checkArtifacts, generateArtifacts, renderInventory } from './gate.mjs';
import { artifacts } from './inventory.mjs';

/** The package root (`packages/website`). */
const packageRoot = fileURLToPath(new URL('../../..', import.meta.url));
/** The repository root — the website package's parent. */
const repoRoot = fileURLToPath(new URL('../../../..', import.meta.url));

/** The one committed artifact the umbrella owns today. */
const GENERATED_PATH = 'app/lib/agent-skills.generated.ts';

/** A temp directory that stands in for a checkout: `generateArtifacts`
 * writes the artifact into it exactly where the committed file would sit. */
function makeFakeRoot(): string {
  const root = mkdtempSync(path.join(os.tmpdir(), 'artifact-gate-root-'));
  mkdirSync(path.join(root, 'app/lib'), { recursive: true });
  return root;
}

/** The banner convention every generated file must carry. */
const BANNER_MARKER = /GENERATED by /;

const TEXT_EXTENSIONS = new Set(['.ts', '.tsx', '.mdx', '.md', '.mjs', '.json', '.txt']);

const tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
  vi.restoreAllMocks();
});

describe('the umbrella artifact gate', () => {
  it('reports a tampered committed artifact as stale, naming its label and fix command', () => {
    const root = makeFakeRoot();
    tempDirs.push(root);
    generateArtifacts({ toDir: root });
    const committedPath = path.join(root, GENERATED_PATH);
    writeFileSync(committedPath, `${readFileSync(committedPath, 'utf8')}\n// hand-edited\n`);
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    const stale = checkArtifacts({ root, skillsRoot: defaultSkillsRoot });

    expect(stale).toBe(true);
    expect(errorSpy.mock.calls.join('\n')).toContain(`ERROR: ${GENERATED_PATH} is stale`);
    expect(errorSpy.mock.calls.join('\n')).toContain('yarn workspace @goodfoot/git-span-website generate:artifacts');
  });

  it('treats a missing committed artifact as stale, not a crash', () => {
    const root = makeFakeRoot();
    tempDirs.push(root);
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    const stale = checkArtifacts({ root, skillsRoot: defaultSkillsRoot });

    expect(stale).toBe(true);
    expect(errorSpy.mock.calls.join('\n')).toContain(GENERATED_PATH);
  });

  it('passes when generate and check run against the same root (generate/check parity)', () => {
    const root = makeFakeRoot();
    tempDirs.push(root);
    generateArtifacts({ toDir: root });

    const stale = checkArtifacts({ root, skillsRoot: defaultSkillsRoot });

    expect(stale).toBe(false);
  });

  it('is deterministic: two generate runs are byte-identical', () => {
    const first = makeFakeRoot();
    const second = makeFakeRoot();
    tempDirs.push(first, second);
    generateArtifacts({ toDir: first });
    generateArtifacts({ toDir: second });

    expect(readFileSync(path.join(first, GENERATED_PATH), 'utf8')).toBe(
      readFileSync(path.join(second, GENERATED_PATH), 'utf8')
    );
  });

  it('emits the served-file map in sorted key order', () => {
    const publication = buildPublication(defaultSkillsRoot);
    const keys = Object.keys(publication.files);

    expect(keys).toEqual([...keys].sort());
  });

  it('holds the banner bijection: every banner-marked committed text file is inventory-listed, and listed generated files carry their banner', () => {
    const committedFiles = execFileSync('git', ['-C', repoRoot, 'ls-files', 'packages/website'], {
      encoding: 'utf8'
    })
      .split('\n')
      .filter((line) => line.length > 0)
      .map((line) => line.replace(/^packages\/website\//, ''));

    const bannerMarked = committedFiles.filter((file) => {
      if (!TEXT_EXTENSIONS.has(path.extname(file))) return false;
      let content: string;
      try {
        content = readFileSync(path.join(packageRoot, file), 'utf8');
      } catch {
        return false;
      }
      const head = content.split('\n').slice(0, 10).join('\n');
      return BANNER_MARKER.test(head);
    });

    const committedGenerated = artifacts.filter((entry) => entry.kind === 'committed-generated');

    for (const file of bannerMarked) {
      const entry = committedGenerated.find((candidate) => candidate.path === file);
      expect(entry, `banner-marked file ${file} must be inventory-listed as committed-generated`).toBeDefined();
    }
    for (const entry of committedGenerated) {
      if (entry.banner !== null) {
        const content = readFileSync(path.join(packageRoot, entry.path), 'utf8');
        expect(content, `${entry.path} must carry its banner`).toContain(entry.banner);
      } else {
        expect(entry.bannerJustification, `${entry.path} is bannerless and must justify it`).toBeTruthy();
      }
    }
  });

  it('names a live renderer and check for every entry, and a fix command for every committed-generated entry', () => {
    for (const entry of artifacts) {
      expect(entry.check, `${entry.label} must declare its check`).toBeTruthy();
      for (const generatorFile of entry.generatorFiles) {
        expect(
          existsSync(path.resolve(packageRoot, generatorFile)),
          `${entry.label} names a renderer that does not exist: ${generatorFile}`
        ).toBe(true);
      }
      if (entry.kind === 'committed-generated') {
        expect(entry.fixCommand, `${entry.label} must declare its fix command`).toBeTruthy();
      }
    }
  });

  it('renders the full inventory with every entry and its source', () => {
    const rendered = renderInventory();

    expect(rendered).toContain('Artifact | Kind | Source');
    for (const entry of artifacts) {
      expect(rendered).toContain(entry.path);
      expect(rendered).toContain(entry.kind);
    }
  });
});
