services:
  app:
    hostname: git-mesh
    extra_hosts:
      - "git-mesh:127.0.0.1"
    init: true
    cap_add:
      - SYS_TIME
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ${HOME}/devcontainer/git-mesh:/home/node:cached
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - CLAUDE_CONFIG_DIR=/home/node/.claude
    dns:
      - 1.1.1.1
    command: sleep infinity
