/**
 * Working-tree scanner: turns a git repository into an immutable
 * {@link RepoScan} snapshot that the rest of the pipeline can mine without
 * touching the filesystem or git again.
 *
 * Filters out noise (lockfiles, caches, logs), generated/compiled/vendored
 * output (build dirs, compiled `.ts` siblings, `@generated` markers,
 * `.gitattributes` linguist rules), and classifies remaining files as text
 * (scannable) or binary/asset (referencable but not content-scanned).
 *
 * @summary Scans a repository working tree into a RepoScan snapshot.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { defaultGitRunner } from './git.js';
import type { DiscoverConfig, GitRunner, RepoScan } from './types.js';

/** Basenames that are noise regardless of location: lockfiles and junk. */
const NOISE_BASENAMES = new Set([
  'yarn.lock',
  'package-lock.json',
  'pnpm-lock.yaml',
  'npm-shrinkwrap.json',
  'Cargo.lock',
  'poetry.lock',
  'Pipfile.lock',
  'go.sum',
  'composer.lock',
  'Gemfile.lock',
  'flake.lock',
  '.DS_Store'
]);

/** Path suffixes that are noise regardless of location. */
const NOISE_SUFFIXES = ['.log', '.tsbuildinfo', '.min.js', '.min.css', '.map'];

/** Path segments that mark every file beneath them as noise. */
const NOISE_SEGMENTS = new Set(['node_modules', '__pycache__', '.cache', '__snapshots__']);

/** Path segments that mark every file beneath them as generated output. */
const GENERATED_SEGMENTS = new Set(['dist', 'build', 'out', 'coverage', '.next']);

/** Suffixes appended to a `.ts`/`.tsx` source's stem by a TypeScript build. */
const COMPILED_SIBLING_SUFFIXES = ['.js', '.mjs', '.cjs', '.d.ts', '.js.map', '.d.ts.map'];

/** Matches the first 400 characters of a file that declares itself generated. */
const GENERATED_HEAD_RE = /@generated|code generated|do not edit|autogenerated|automatically generated/i;

/** Extensions classified as binary/asset (kept as referencable targets, never scanned as text). */
const BINARY_EXTENSIONS = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.icns',
  '.woff',
  '.woff2',
  '.ttf',
  '.otf',
  '.eot',
  '.zip',
  '.gz',
  '.tar',
  '.tgz',
  '.jar',
  '.pdf',
  '.mp4',
  '.mov',
  '.webm',
  '.mp3',
  '.wav',
  '.vsix',
  '.node',
  '.wasm',
  '.db',
  '.sqlite'
]);

/** Number of leading bytes inspected for a NUL byte when sniffing for binary content. */
const BINARY_SNIFF_BYTES = 8192;

/** Number of leading characters inspected for a generated-file marker. */
const GENERATED_HEAD_CHARS = 400;

/** Extensions that count toward a directory's documentation-file ratio. */
const DOCS_EXTENSIONS = new Set(['.md', '.mdx', '.rst', '.adoc']);

/** Minimum number of files a directory prefix must contain to be considered for docsDirs. */
const DOCS_MIN_FILES = 3;

/** Minimum share of documentation-extension files for a directory to classify as docs. */
const DOCS_MIN_RATIO = 0.6;

/**
 * Scan the working tree of the git repository at `root` into a
 * {@link RepoScan}.
 *
 * @param root - Absolute path to the repository root.
 * @param config - Resolved discovery configuration (see `resolveConfig`).
 * @param git - Git command runner; defaults to {@link defaultGitRunner}.
 * @returns Immutable snapshot of tracked, referencable files and their
 *   scannable text content.
 * @throws {Error} If git invocation fails, or a tracked file cannot be read.
 */
export function scanRepo(root: string, config: DiscoverConfig, git: GitRunner = defaultGitRunner): RepoScan {
  const tracked = listTrackedFiles(root, git);
  const notExcluded = tracked.filter((file) => !isExcluded(file, config.exclude));
  const candidates = notExcluded.filter((file) => !isNoise(file));

  const generatedBySegment = candidates.filter(isGeneratedSegment);
  const generatedBySiblings = computeCompiledSiblings(candidates);
  const generatedByAttributes = computeGitattributesGenerated(candidates, root);
  const structurallyGenerated = new Set<string>([
    ...generatedBySegment,
    ...generatedBySiblings,
    ...generatedByAttributes
  ]);

  const remaining = candidates.filter((file) => !structurallyGenerated.has(file));

  const files: string[] = [];
  const text = new Map<string, string>();
  for (const file of remaining) {
    // git also tracks symlinks and submodule gitlinks; keep them referencable
    // but never follow or read them (a link may point outside the repo or
    // into an excluded tree).
    const stat = lstatTracked(root, file);
    const ext = path.extname(file).toLowerCase();
    if (!stat.isFile() || BINARY_EXTENSIONS.has(ext) || stat.size > config.maxFileBytes) {
      files.push(file);
      continue;
    }
    const buffer = readTrackedFile(root, file);
    if (buffer.subarray(0, BINARY_SNIFF_BYTES).includes(0)) {
      files.push(file);
      continue;
    }
    const content = buffer.toString('utf8');
    if (GENERATED_HEAD_RE.test(content.slice(0, GENERATED_HEAD_CHARS))) {
      continue;
    }
    files.push(file);
    text.set(file, content);
  }
  files.sort();

  const lines = new Map<string, readonly string[]>();
  for (const [file, content] of text) {
    lines.set(file, content.split(/\r?\n/));
  }

  const topLevelDirs = new Set<string>();
  for (const file of files) {
    const slash = file.indexOf('/');
    if (slash >= 0) {
      topLevelDirs.add(file.slice(0, slash));
    }
  }

  return { root, files, text, lines, topLevelDirs, docsDirs: computeDocsDirs(files) };
}

/**
 * List every file git tracks in `root`, in the NUL-delimited form `git
 * ls-files -z` reports (no filtering applied yet).
 *
 * @param root - Absolute path to the repository root.
 * @param git - Git command runner.
 * @returns Repository-relative POSIX paths of every tracked file.
 */
function listTrackedFiles(root: string, git: GitRunner): string[] {
  const output = git(['ls-files', '-z'], root);
  return output.split('\0').filter((entry) => entry.length > 0);
}

/**
 * Whether `file` is equal to, or nested under, one of the configured exclude
 * prefixes.
 *
 * @param file - Repository-relative POSIX path.
 * @param exclude - Normalized exclude prefixes (see `resolveConfig`).
 * @returns True if `file` should be dropped entirely.
 */
function isExcluded(file: string, exclude: readonly string[]): boolean {
  return exclude.some((prefix) => prefix === file || file.startsWith(`${prefix}/`));
}

/**
 * Whether `file` is noise (lockfiles, caches, logs) that should never appear
 * in a scan, regardless of its content.
 *
 * @param file - Repository-relative POSIX path.
 * @returns True if `file` is noise.
 */
function isNoise(file: string): boolean {
  if (NOISE_BASENAMES.has(path.basename(file))) {
    return true;
  }
  if (NOISE_SUFFIXES.some((suffix) => file.endsWith(suffix))) {
    return true;
  }
  return file.split('/').some((segment) => NOISE_SEGMENTS.has(segment));
}

/**
 * Whether `file` lives under a path segment that marks build output (`dist`,
 * `build`, `out`, `coverage`, `.next`).
 *
 * @param file - Repository-relative POSIX path.
 * @returns True if `file` is generated by virtue of its location.
 */
function isGeneratedSegment(file: string): boolean {
  return file.split('/').some((segment) => GENERATED_SEGMENTS.has(segment));
}

/**
 * Find every compiled sibling (`.js`, `.mjs`, `.cjs`, `.d.ts`, `.js.map`,
 * `.d.ts.map`) of a tracked `.ts`/`.tsx` source that also survives in
 * `candidates`, per {@link COMPILED_SIBLING_SUFFIXES}.
 *
 * @param candidates - Tracked files remaining after exclude/noise filtering.
 * @returns The set of candidate paths that are compiled siblings.
 */
function computeCompiledSiblings(candidates: readonly string[]): Set<string> {
  const candidateSet = new Set(candidates);
  const generated = new Set<string>();
  for (const file of candidates) {
    let stem: string;
    if (file.endsWith('.tsx')) {
      stem = file.slice(0, -'.tsx'.length);
    } else if (file.endsWith('.ts') && !file.endsWith('.d.ts')) {
      stem = file.slice(0, -'.ts'.length);
    } else {
      continue;
    }
    for (const suffix of COMPILED_SIBLING_SUFFIXES) {
      const sibling = `${stem}${suffix}`;
      if (candidateSet.has(sibling)) {
        generated.add(sibling);
      }
    }
  }
  return generated;
}

/**
 * Escape every regex metacharacter in `literal` so it matches only itself.
 *
 * @param literal - Raw text with no wildcard meaning.
 * @returns `literal`, safe to embed in a `RegExp` source string.
 */
function escapeRegExp(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Compile a `.gitattributes` pattern into a `RegExp` that matches a path
 * relative to the attributes file's directory. Supports literal path
 * segments, `*` (matches within one path segment), `**` (matches across
 * segments), and a trailing `dir/` form (equivalent to `dir/**`).
 *
 * @param rawPattern - Pattern token as written in the `.gitattributes` file.
 * @returns Regular expression anchored to match the full relative path.
 */
function gitattributesPatternToRegExp(rawPattern: string): RegExp {
  const pattern = rawPattern.endsWith('/') ? `${rawPattern}**` : rawPattern;
  const tokens = pattern.match(/\*\*|\*|[^*]+/g) ?? [];
  const source = tokens
    .map((token) => {
      if (token === '**') {
        return '.*';
      }
      if (token === '*') {
        return '[^/]*';
      }
      return escapeRegExp(token);
    })
    .join('');
  return new RegExp(`^${source}$`);
}

/**
 * Directory a `.gitattributes` file's patterns are relative to.
 *
 * @param attrFile - Repository-relative POSIX path to the attributes file.
 * @returns The parent directory, or `''` when the file lives at the root.
 */
function gitattributesDir(attrFile: string): string {
  const dir = path.dirname(attrFile);
  return dir === '.' ? '' : dir;
}

/**
 * Express `file` relative to `attrDir`, or `undefined` when `file` does not
 * live under `attrDir` at all.
 *
 * @param file - Repository-relative POSIX path.
 * @param attrDir - Directory a `.gitattributes` file's patterns are relative to.
 * @returns The path of `file` relative to `attrDir`, if it is nested under it.
 */
function relativeToAttrDir(file: string, attrDir: string): string | undefined {
  if (attrDir === '') {
    return file;
  }
  return file.startsWith(`${attrDir}/`) ? file.slice(attrDir.length + 1) : undefined;
}

/**
 * Parse `linguist-generated`/`linguist-vendored` rules out of one
 * `.gitattributes` file's content, keeping only entries where the attribute
 * is "on" (bare, or explicitly `=true`).
 *
 * @param content - Raw content of the `.gitattributes` file.
 * @param attrName - Attribute to look for (`linguist-generated` or `linguist-vendored`).
 * @returns Compiled pattern matchers for every "on" rule naming `attrName`.
 */
function parseGitattributesRules(content: string, attrName: string): RegExp[] {
  const rules: RegExp[] = [];
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) {
      continue;
    }
    const tokens = line.split(/\s+/);
    const patternToken = tokens[0];
    if (patternToken === undefined || patternToken === '') {
      continue;
    }
    const attrTokens = tokens.slice(1);
    const isOn = attrTokens.includes(attrName) || attrTokens.includes(`${attrName}=true`);
    if (isOn) {
      rules.push(gitattributesPatternToRegExp(patternToken));
    }
  }
  return rules;
}

/**
 * Find every candidate marked `linguist-generated` or `linguist-vendored` by
 * a tracked `.gitattributes` file (root or nested).
 *
 * @param candidates - Tracked files remaining after exclude/noise filtering.
 * @param root - Absolute path to the repository root.
 * @returns The set of candidate paths matched by an "on" linguist rule.
 */
function computeGitattributesGenerated(candidates: readonly string[], root: string): Set<string> {
  const generated = new Set<string>();
  const attrFiles = candidates.filter((file) => path.basename(file) === '.gitattributes');
  for (const attrFile of attrFiles) {
    // git refuses to honor a symlinked .gitattributes — attribute rules are
    // read from regular files only — so non-regular entries contribute none.
    if (!lstatTracked(root, attrFile).isFile()) {
      continue;
    }
    const attrDir = gitattributesDir(attrFile);
    const content = readTrackedFile(root, attrFile).toString('utf8');
    const rules = [
      ...parseGitattributesRules(content, 'linguist-generated'),
      ...parseGitattributesRules(content, 'linguist-vendored')
    ];
    if (rules.length === 0) {
      continue;
    }
    for (const file of candidates) {
      if (generated.has(file)) {
        continue;
      }
      const relative = relativeToAttrDir(file, attrDir);
      if (relative !== undefined && rules.some((rule) => rule.test(relative))) {
        generated.add(file);
      }
    }
  }
  return generated;
}

/**
 * `lstat` one tracked path without following symlinks, failing closed on any
 * error (a racing deletion, a permissions problem, and so on) rather than
 * skipping the entry.
 *
 * @param root - Absolute path to the repository root.
 * @param file - Repository-relative POSIX path.
 * @returns The entry's lstat result.
 * @throws {Error} If the path cannot be stat'ed.
 */
function lstatTracked(root: string, file: string): fs.Stats {
  try {
    return fs.lstatSync(path.join(root, file));
  } catch (error) {
    throw new Error(`discover: failed to stat tracked file '${file}'`, { cause: error });
  }
}

/**
 * Read one tracked file's raw bytes, failing closed on any error (a racing
 * deletion, a permissions problem, and so on) rather than skipping it.
 *
 * @param root - Absolute path to the repository root.
 * @param file - Repository-relative POSIX path.
 * @returns The file's complete content as a `Buffer`.
 * @throws {Error} If the file cannot be read.
 */
function readTrackedFile(root: string, file: string): Buffer {
  try {
    return fs.readFileSync(path.join(root, file));
  } catch (error) {
    throw new Error(`discover: failed to read tracked file '${file}'`, { cause: error });
  }
}

/**
 * Classify every depth-1 or depth-2 directory prefix with at least
 * {@link DOCS_MIN_FILES} files and a documentation-extension share of at
 * least {@link DOCS_MIN_RATIO} as a docs directory, dropping any prefix
 * nested inside another qualifying prefix.
 *
 * @param files - Final scanned files (post-filtering), sorted ascending.
 * @returns Sorted docs directory prefixes, each with a trailing `/`.
 */
function computeDocsDirs(files: readonly string[]): string[] {
  const counts = new Map<string, { total: number; docs: number }>();
  for (const file of files) {
    const segments = file.split('/');
    for (const depth of [1, 2]) {
      if (segments.length <= depth) {
        continue;
      }
      const prefix = segments.slice(0, depth).join('/');
      const entry = counts.get(prefix) ?? { total: 0, docs: 0 };
      entry.total += 1;
      if (DOCS_EXTENSIONS.has(path.extname(file).toLowerCase())) {
        entry.docs += 1;
      }
      counts.set(prefix, entry);
    }
  }

  const qualifying: string[] = [];
  for (const [prefix, { total, docs }] of counts) {
    if (total >= DOCS_MIN_FILES && docs / total >= DOCS_MIN_RATIO) {
      qualifying.push(prefix);
    }
  }

  const result = qualifying.filter(
    (prefix) => !qualifying.some((other) => other !== prefix && prefix.startsWith(`${other}/`))
  );
  result.sort();
  return result.map((prefix) => `${prefix}/`);
}
