#!/usr/bin/env bash
# Rebrand "git mesh" -> "git span" across the entire repository: source,
# docs, usage text, package/crate/directory names, and the .mesh data
# directory (-> .span). One-shot migration; delete this script once applied.
#
# Usage:
#   ./scripts/rebrand-mesh-to-span.sh              # dry run (default): report only
#   ./scripts/rebrand-mesh-to-span.sh --diff [p..] # dry run + unified diff (all or given paths)
#   ./scripts/rebrand-mesh-to-span.sh --apply      # rewrite contents, git mv paths, rebuild,
#                                                  # re-anchor .span files, verify, validate
#
# Flags:
#   --apply              Perform the rewrite (requires a clean tracked worktree).
#   --skip-post          With --apply: skip rebuild / re-anchor / yarn validate
#                        (used for testing the mechanical rewrite in isolation).
#   --no-extent-prepass  Skip the disambiguation pass that renames the OLD
#                        line-range sense of "span" to "extent" before "mesh"
#                        takes over the word "span".
#   --diff [paths...]    Dry run only: print the unified diff of the content
#                        rewrite (for all files, or just the given paths).
#
# What it does, in order:
#   1. Extent pre-pass: the codebase already uses "span" for an anchor's
#      line-range (docs also call it "extent"). To keep "span" unambiguous
#      after the rebrand, that old sense is renamed to "extent":
#        - global identifier renames (line_range_span -> line_range_extent, ...)
#        - whole-word span->extent in the three files where it is the
#          line-range variable (core lib.rs, core benches/scan.rs, anchor.rs)
#        - curated prose fixes (exact phrases, each expected exactly once)
#      Verb uses ("spans three files") and perf-tracing spans are untouched.
#   2. Content rewrite of every tracked text file, longest token first:
#      meshes->spans, meshing->spanning, meshed->spanned, mesh->span,
#      in all three case shapes (lower/Title/UPPER).
#   3. Path renames via `git mv` for every tracked path containing "mesh"
#      (packages/git-mesh -> packages/git-span, .mesh/ -> .span/, ...).
#   4. Post steps (unless --skip-post): yarn install, rebuild the bundled
#      agent hooks (their base64 source maps embed the old name), build the
#      git-span binary, then `git span stale --fix` to re-anchor the .span
#      files whose anchored content this rewrite changed, and `git span
#      stale` must come back clean.
#   5. Verification: no case-insensitive "mesh" remains in tracked content
#      or paths (this script excepted; base64 lines are warned, they are
#      regenerated by the hook rebuild in step 4).
#   6. Final gate (unless --skip-post): `yarn validate` must exit 0.
#
# NOT covered (by design): the GitHub repo rename itself (in-repo URLs are
# rewritten to goodfoot-io/git-span; rename the repo on GitHub separately),
# git history, and the shared cargo cache at ~/.cache/git-mesh (the new
# name simply starts a fresh cache at ~/.cache/git-span).

set -euo pipefail
LC_ALL=C
export LC_ALL

cd "$(git rev-parse --show-toplevel)"

SELF="scripts/rebrand-mesh-to-span.sh"

MODE=dry
SKIP_POST=0
PREPASS=1
SHOW_DIFF=0
DIFF_PATHS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --apply) MODE=apply ;;
        --dry-run) MODE=dry ;;
        --skip-post) SKIP_POST=1 ;;
        --no-extent-prepass) PREPASS=0 ;;
        --diff) SHOW_DIFF=1 ;;
        --*) echo "unknown flag: $1" >&2; exit 2 ;;
        *) DIFF_PATHS+=("$1") ;;
    esac
    shift
done

if [ "$SHOW_DIFF" -eq 1 ] && [ "$MODE" = apply ]; then
    echo "--diff is a dry-run option; drop --apply to preview" >&2
    exit 2
fi

say()  { printf '%s\n' "$*"; }
head_ln() { printf '\n== %s ==\n' "$*"; }

# ---------------------------------------------------------------------------
# The rewrite programs
# ---------------------------------------------------------------------------

# Step 2: mesh -> span, longest token first so "meshes" never becomes "spanes".
MAIN_SED='
s/MESHES/SPANS/g; s/MESHING/SPANNING/g; s/MESHED/SPANNED/g; s/MESH/SPAN/g
s/Meshes/Spans/g; s/Meshing/Spanning/g; s/Meshed/Spanned/g; s/Mesh/Span/g
s/meshes/spans/g; s/meshing/spanning/g; s/meshed/spanned/g; s/mesh/span/g
'

# Step 1a: identifier renames, safe everywhere.
PREPASS_GLOBAL_SED='
s/line_range_span/line_range_extent/g
s/scan_spans/scan_extents/g
s/load_spans/load_extents/g
'

# Step 1b: files where whole-word "span" is always the line-range noun
# (verified by hand; none of these call perf::span).
PREPASS_BLANKET_FILES=(
    packages/git-mesh-core/src/lib.rs
    packages/git-mesh-core/benches/scan.rs
    packages/git-mesh/src/resolver/engine/anchor.rs
)
PREPASS_BLANKET_SED='
s/\bSpans\b/Extents/g; s/\bspans\b/extents/g
s/\bSpan\b/Extent/g;   s/\bspan\b/extent/g
'

# Step 1c: curated prose fixes. Format: <file>|<sed expression>.
# Each pattern is expected to match exactly once; a miss aborts the run.
PREPASS_CURATED=(
    'packages/git-mesh/src/cli/stale_fix.rs|s/member indices, span, and/member indices, extent, and/'
    'plugins/git-mesh/skills/git-mesh/sections/responding-to-drift.md|s/`git mesh remove` the old span/`git mesh remove` the old extent/'
    'plugins/git-mesh/skills/git-mesh/sections/responding-to-drift.md|s/you pinned the wrong span/you pinned the wrong extent/'
    'plugins/git-mesh/skills/git-mesh/sections/responding-to-drift.md|s/over the identical span/over the identical extent/'
    'plugins/git-mesh/skills/git-mesh/sections/responding-to-drift.md|s/Different line span/Different line extent/'
    'plugins/git-mesh/skills/git-mesh/sections/responding-to-drift.md|s/A span that does not exactly match/An extent that does not exactly match/'
    'packages/agent-hooks/src/agent-prompt.md|s/over an existing span re-anchors it/over an existing extent re-anchors it/'
    'packages/agent-hooks/src/agent-prompt.md|s/a moved span needs/a moved extent needs/'
    'packages/agent-hooks/src/agent-prompt.md|s/`add` the new span/`add` the new extent/'
    'plugins/git-mesh/skills/git-mesh/sections/terminal-statuses.md|s/re-anchor at the new span/re-anchor at the new extent/'
    'plugins/git-mesh/skills/git-mesh/sections/standalone-reconciler.md|s/hints, not exact spans/hints, not exact extents/'
)

# Full per-file rewrite pipeline (pre-pass + main pass) on stdin -> stdout.
rewrite_stream() {
    local file="$1"
    local prog=""
    if [ "$PREPASS" -eq 1 ]; then
        prog+="$PREPASS_GLOBAL_SED"
        local blanket
        for blanket in "${PREPASS_BLANKET_FILES[@]}"; do
            if [ "$file" = "$blanket" ]; then
                prog+="$PREPASS_BLANKET_SED"
            fi
        done
        local entry
        for entry in "${PREPASS_CURATED[@]}"; do
            if [ "${entry%%|*}" = "$file" ]; then
                prog+="${entry#*|}"$'\n'
            fi
        done
    fi
    prog+="$MAIN_SED"
    sed -e "$prog"
}

map_path() {
    printf '%s' "$1" | sed -e "$MAIN_SED"
}

# ---------------------------------------------------------------------------
# Enumerate tracked files (this script excluded)
# ---------------------------------------------------------------------------

# Refuse symlinks: sed -i would rewrite the target through the link.
if git ls-files -s | awk '$1 == 120000 { exit 1 }'; then :; else
    echo "tracked symlinks present; teach the script about them first" >&2
    exit 1
fi

mapfile -d '' -t FILES < <(git ls-files -z)

TEXT_FILES=()
for f in "${FILES[@]}"; do
    [ "$f" = "$SELF" ] && continue
    TEXT_FILES+=("$f")
done

# ---------------------------------------------------------------------------
# Pre-flight report (both modes)
# ---------------------------------------------------------------------------

OCCURRENCES=$(git grep -oiI mesh -- ":!$SELF" | wc -l)
CONTENT_FILES=$(git grep -liI mesh -- ":!$SELF" | wc -l)

head_ln "rebrand mesh -> span ($MODE run)"
say "tracked files:                 ${#FILES[@]}"
say "files with 'mesh' in content:  $CONTENT_FILES"
say "'mesh' occurrences (any case): $OCCURRENCES"

if [ "$PREPASS" -eq 1 ]; then
    head_ln "step 1: extent pre-pass (old line-range sense of 'span' -> 'extent')"
    say "global identifier renames: line_range_span, scan_spans, load_spans -> *_extent(s)"
    for f in "${PREPASS_BLANKET_FILES[@]}"; do
        n=$(git grep -cwI 'span\|spans\|Span\|Spans' -- "$f" 2>/dev/null | cut -d: -f2 || echo 0)
        say "whole-word span -> extent: $f ($n lines)"
    done
    MISS=0
    for entry in "${PREPASS_CURATED[@]}"; do
        file="${entry%%|*}"; expr="${entry#*|}"
        pat="${expr#s/}"; pat="${pat%%/*}"
        hits=$(grep -cF "$(printf '%s' "$pat" | sed 's/\\b//g')" "$file" 2>/dev/null || echo 0)
        if [ "$hits" -ne 1 ]; then
            say "CURATED PATTERN MISS ($hits matches, want 1): $file :: $pat"
            MISS=1
        else
            say "curated: $file :: $pat"
        fi
    done
    if [ "$MISS" -ne 0 ]; then
        echo "curated pre-pass patterns out of date; fix the list before running" >&2
        exit 1
    fi
else
    head_ln "step 1: extent pre-pass SKIPPED (--no-extent-prepass)"
fi

head_ln "step 3: path renames (git mv)"
RENAME_OLD=()
RENAME_NEW=()
for f in "${TEXT_FILES[@]}"; do
    case "$f" in
        *[Mm]esh*)
            new=$(map_path "$f")
            RENAME_OLD+=("$f")
            RENAME_NEW+=("$new")
            say "  $f -> $new"
            ;;
    esac
done
say "total renames: ${#RENAME_OLD[@]}"

head_ln "step 4-6: post steps (apply mode)"
if [ "$SKIP_POST" -eq 1 ]; then
    say "SKIPPED (--skip-post): yarn install; rebuild agent hooks; build git-span;"
    say "  git span stale --fix; verification still runs; yarn validate skipped"
else
    say "yarn install                      # refresh lockfile state after package renames"
    say "yarn workspace agent-hooks build  # regenerate bundled hooks (base64 source maps)"
    say "yarn workspace @goodfoot/git-span build   # git-span release binary + man page"
    say "git span stale --fix && git span stale    # re-anchor .span files, confirm clean"
    say "yarn validate                     # full typecheck/lint/test/build gate"
fi

# ---------------------------------------------------------------------------
# Dry run: optionally show the content diff, then stop.
# ---------------------------------------------------------------------------

if [ "$MODE" = dry ]; then
    if [ "$SHOW_DIFF" -eq 1 ]; then
        head_ln "content diff preview"
        if [ ${#DIFF_PATHS[@]} -gt 0 ]; then
            PREVIEW=("${DIFF_PATHS[@]}")
        else
            mapfile -t PREVIEW < <(git grep -liI mesh -- ":!$SELF")
        fi
        for f in "${PREVIEW[@]}"; do
            rewrite_stream "$f" <"$f" | diff -u --label "a/$f" --label "b/$f" "$f" - || true
        done
    fi
    head_ln "dry run complete — nothing changed. Re-run with --apply to execute."
    exit 0
fi

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    echo "tracked worktree is not clean; commit or stash first" >&2
    exit 1
fi

head_ln "applying content rewrite"
CHANGED=0
for f in "${TEXT_FILES[@]}"; do
    # Skip files git considers binary (none contain 'mesh' today, but stay safe).
    if ! git grep -qiI mesh -- "$f" && [ "$PREPASS" -eq 0 ]; then
        continue
    fi
    tmp="$f.rebrand.tmp"
    rewrite_stream "$f" <"$f" >"$tmp"
    if cmp -s "$f" "$tmp"; then
        rm -f "$tmp"
    else
        chmod --reference="$f" "$tmp"
        mv "$tmp" "$f"
        CHANGED=$((CHANGED + 1))
    fi
done
say "files rewritten: $CHANGED"

head_ln "applying path renames"
for i in "${!RENAME_OLD[@]}"; do
    old="${RENAME_OLD[$i]}"; new="${RENAME_NEW[$i]}"
    mkdir -p "$(dirname "$new")"
    git mv "$old" "$new"
done
say "paths renamed: ${#RENAME_OLD[@]}"

if [ "$SKIP_POST" -eq 0 ]; then
    head_ln "post: yarn install"
    yarn install

    head_ln "post: rebuild bundled agent hooks"
    yarn workspace agent-hooks build

    head_ln "post: build git-span"
    yarn workspace @goodfoot/git-span build

    head_ln "post: re-anchor .span files"
    BIN_DIR="${GIT_SPAN_CARGO_TARGET_ROOT:-$HOME/.cache/git-span/cargo-target}/git-span/build/release"
    if [ ! -x "$BIN_DIR/git-span" ]; then
        echo "expected binary at $BIN_DIR/git-span not found" >&2
        exit 1
    fi
    PATH="$BIN_DIR:$PATH" git span stale --fix || true
    PATH="$BIN_DIR:$PATH" git span stale
fi

head_ln "verification: no 'mesh' left behind"
FAIL=0
if git ls-files | grep -i mesh | grep -vxF "$SELF" ; then
    say "FAIL: tracked paths above still contain 'mesh'"
    FAIL=1
fi
RESIDUAL=$(git grep -inI mesh -- ":!$SELF" || true)
if [ -n "$RESIDUAL" ]; then
    HARD=$(printf '%s\n' "$RESIDUAL" | grep -v 'base64,' || true)
    SOFT=$(printf '%s\n' "$RESIDUAL" | grep 'base64,' || true)
    if [ -n "$SOFT" ]; then
        say "WARN: coincidental 'mesh' inside base64 blobs (regenerated by hook rebuild):"
        printf '%s\n' "$SOFT" | cut -c1-120
    fi
    if [ -n "$HARD" ]; then
        say "FAIL: residual 'mesh' in tracked content:"
        printf '%s\n' "$HARD" | cut -c1-160
        FAIL=1
    fi
fi
if [ "$FAIL" -ne 0 ]; then
    echo "verification failed" >&2
    exit 1
fi
say "verification passed"

if [ "$SKIP_POST" -eq 0 ]; then
    head_ln "final gate: yarn validate"
    yarn validate
fi

head_ln "done"
say "review with: git status; git diff --stat HEAD"
say "this script is now the only file still named 'mesh' — delete it after committing."
